from tkinter import *
def click(event):
    global scvalue
    text = event.widget.cget("text")
    if text == "=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
            scvalue1.set(value)
        else:
            try:
                value = eval(screen.get())
            except Exception as e:
                value="Error"
        scvalue1.set("Error")
        screen.update()
        scvalue1.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        scvalue1.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root=Tk()
root.geometry("400x520")
root.minsize("400","510")
root.maxsize("500","620")
root.title("Calculator")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvariable=scvalue,font="lucida 15 bold",borderwidth=3,relief=GROOVE)
screen.pack(ipadx=5,ipady=5,padx=5,pady=8,fill=X,side=TOP)
f=Frame(root,bg="light grey")
scvalue1=StringVar()
scvalue1.set("")
screen1=Entry(root,textvariable=scvalue1,font="lucida 15 bold",borderwidth=3,relief=GROOVE)
screen1.pack(ipadx=5,ipady=5,padx=10,pady=10,side=TOP)
f.pack()
f=Frame(root,bg="light grey")
b=Button(f,text="9",font="lucida 10 bold",padx=19,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="8",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="7",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="/",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)

f.pack()

f=Frame(root,bg="light grey")

b=Button(f,text="6",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="5",font="lucida 10 bold",padx=19,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="4",font="lucida 10 bold",padx=21,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="*",font="lucida 10 bold",padx=18,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)

f.pack()

f=Frame(root,bg="light grey")

b=Button(f,text="3",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="2",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="1",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="-",font="lucida 10 bold",padx=19,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
f.pack()

f=Frame(root,bg="light grey")
b=Button(f,text="%",font="lucida 10 bold",padx=19,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="0",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text=".",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="+",font="lucida 10 bold",padx=18,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
f.pack()

f=Frame(root,bg="light grey")
b=Button(f,text="C",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="(",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text=")",font="lucida 10 bold",padx=20,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
b=Button(f,text="=",font="lucida 10 bold",padx=19,pady=20)
b.pack(side=LEFT,padx=5,pady=5)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()
